### ISSUE TITLE
NCCL.h not found

### ISSUE THREAD

**Issue by RohitSingh1226** [Luodian/Generalizable-Mixture-of-Experts#11]
Hi @Luodian, I saw the issue you raised on the tutel repository, your suggestion is to install it with apt, but it is still failing for me. My CUDA version is 12.4, I tried to downgrade my torch, torch vision packages but it did not help

Also tried to install nccl from their source repository, it did not work. Do you have a workaround for this

**Comment by moienr** [comment]
Hey @RohitSingh1226 

This fixed the build issue for me when trying to install `tutel`:

```bash
sudo apt install libnccl2 libnccl-dev
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
```
